# Generated by Django 4.2.4 on 2023-09-14 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('htmlapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('S_id', models.CharField(max_length=255, unique=True)),
                ('S_name', models.CharField(max_length=255)),
                ('S_category', models.CharField(max_length=255)),
                ('S_totalfee', models.IntegerField(null=True)),
                ('S_paid', models.IntegerField(null=True)),
                ('S_due', models.IntegerField(null=True)),
            ],
            options={
                'ordering': ['S_name'],
            },
        ),
        migrations.DeleteModel(
            name='classes',
        ),
    ]
