# Generated by Django 4.2.4 on 2023-09-14 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('htmlapp', '0003_filesupload'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='S_branch',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='students',
            name='S_buildingfee',
            field=models.IntegerField(null=True),
        ),
    ]
