# Generated by Django 4.2.4 on 2023-09-14 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('htmlapp', '0005_alter_students_s_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='S_id',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
